Repository sk-prj-genai-question-app/backend, pull requests merged in 2025-07, with the labels that each got.

#2 setup db
  .github/workflows/main.yml
  logs/spring.log
  src/main/java/com/rookies3/genaiquestionapp/GenAiQuestionAppApplication.java
  src/main/java/com/rookies3/genaiquestionapp/auth/entity/User.java
  src/main/resources/application-prod.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
Labels: feature

#7 feat: 문제 생성 후 저장 구현, 기타 수정
  src/main/java/com/rookies3/genaiquestionapp/config/SecurityConfig.java
  src/main/java/com/rookies3/genaiquestionapp/controller/ProblemController.java
  src/main/java/com/rookies3/genaiquestionapp/dto/ChoiceDto.java
  src/main/java/com/rookies3/genaiquestionapp/dto/ProblemDto.java
  src/main/java/com/rookies3/genaiquestionapp/entity/BaseEntity.java
  src/main/java/com/rookies3/genaiquestionapp/entity/Choice.java
  src/main/java/com/rookies3/genaiquestionapp/entity/Problem.java
  src/main/java/com/rookies3/genaiquestionapp/entity/User.java
  src/main/java/com/rookies3/genaiquestionapp/exception/GlobalExceptionHandler.java
  src/main/java/com/rookies3/genaiquestionapp/repository/ChoiceRepository.java
  src/main/java/com/rookies3/genaiquestionapp/repository/ProblemRepository.java
  src/main/java/com/rookies3/genaiquestionapp/service/ProblemService.java
  src/main/resources/application-prod.properties
  src/main/resources/application-prod.yml
  src/main/resources/application-test.properties
  src/main/resources/application-test.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feature

#11 Dev/1.0.1 merge with main
  .env
  .gitignore
  build.gradle
  src/main/java/com/rookies3/genaiquestionapp/GenAiQuestionAppApplication.java
  src/main/java/com/rookies3/genaiquestionapp/auth/config/SecurityConfig.java
  src/main/java/com/rookies3/genaiquestionapp/auth/controller/AuthController.java
  src/main/java/com/rookies3/genaiquestionapp/auth/controller/dto/AccessTokenDto.java
  src/main/java/com/rookies3/genaiquestionapp/auth/controller/dto/LoginDto.java
  src/main/java/com/rookies3/genaiquestionapp/auth/controller/dto/SignupDto.java
  src/main/java/com/rookies3/genaiquestionapp/auth/controller/dto/TokenDto.java
  src/main/java/com/rookies3/genaiquestionapp/auth/entity/CustomUserDetails.java
  src/main/java/com/rookies3/genaiquestionapp/auth/entity/RefreshToken.java
  src/main/java/com/rookies3/genaiquestionapp/auth/entity/User.java
  src/main/java/com/rookies3/genaiquestionapp/auth/repository/RefreshTokenRepository.java
  src/main/java/com/rookies3/genaiquestionapp/auth/repository/UserRepository.java
  src/main/java/com/rookies3/genaiquestionapp/auth/service/AuthService.java
  src/main/java/com/rookies3/genaiquestionapp/auth/service/CustomUserDetailsService.java
  src/main/java/com/rookies3/genaiquestionapp/auth/service/RefreshTokenService.java
  src/main/java/com/rookies3/genaiquestionapp/entity/BaseEntity.java
  src/main/java/com/rookies3/genaiquestionapp/exception/BusinessException.java
  src/main/java/com/rookies3/genaiquestionapp/exception/ErrorCode.java
  src/main/java/com/rookies3/genaiquestionapp/exception/global/CustomError.java
  src/main/java/com/rookies3/genaiquestionapp/exception/global/ErrorDetail.java
  src/main/java/com/rookies3/genaiquestionapp/exception/global/ErrorResponse.java
  src/main/java/com/rookies3/genaiquestionapp/exception/global/GlobalExceptionHandler.java
  src/main/java/com/rookies3/genaiquestionapp/exception/global/SuccessResponse.java
  src/main/java/com/rookies3/genaiquestionapp/jwt/JwtAuthenticationFilter.java
  src/main/java/com/rookies3/genaiquestionapp/jwt/JwtTokenProvider.java
  src/main/java/com/rookies3/genaiquestionapp/problem/controller/ProblemController.java
  src/main/java/com/rookies3/genaiquestionapp/problem/controller/dto/ChoiceDto.java
  src/main/java/com/rookies3/genaiquestionapp/problem/controller/dto/ProblemDto.java
  src/main/java/com/rookies3/genaiquestionapp/problem/entity/Choice.java
  src/main/java/com/rookies3/genaiquestionapp/problem/entity/Problem.java
  src/main/java/com/rookies3/genaiquestionapp/problem/repository/ChoiceRepository.java
  src/main/java/com/rookies3/genaiquestionapp/problem/repository/ProblemRepository.java
  src/main/java/com/rookies3/genaiquestionapp/problem/service/ProblemService.java
  src/main/java/com/rookies3/genaiquestionapp/record/controller/AnswerRecordController.java
  src/main/java/com/rookies3/genaiquestionapp/record/controller/dto/AnswerRecordDto.java
  src/main/java/com/rookies3/genaiquestionapp/record/entity/AnswerRecord.java
  src/main/java/com/rookies3/genaiquestionapp/record/repository/AnswerRecordRepository.java
  src/main/java/com/rookies3/genaiquestionapp/record/service/AnswerRecordService.java
  src/main/java/com/rookies3/genaiquestionapp/util/SecurityUtil.java
  src/main/resources/application-prod.properties
  src/main/resources/application-prod.yml
  src/main/resources/application-test.properties
  src/main/resources/application-test.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/rookies3/genaiquestionapp/GenAiQuestionAppApplicationTests.java
Labels: feature

#15 [ENHANCE] 사용자 ID 처리 방식 개선 및 보안 강화 (인증 기반으로 변경)
  src/main/java/com/rookies3/genaiquestionapp/problem/controller/ProblemController.java
  src/main/java/com/rookies3/genaiquestionapp/record/controller/AnswerRecordController.java
  src/main/java/com/rookies3/genaiquestionapp/record/controller/dto/AnswerRecordDto.java
  src/main/java/com/rookies3/genaiquestionapp/record/service/AnswerRecordService.java
Labels: enhancement

#22 [BUG] 풀이 기록 db중복 생성 문제 해결
  src/main/java/com/rookies3/genaiquestionapp/record/entity/AnswerRecord.java
  src/main/java/com/rookies3/genaiquestionapp/record/repository/AnswerRecordRepository.java
  src/main/java/com/rookies3/genaiquestionapp/record/service/AnswerRecordService.java
  src/main/resources/application.yml
Labels: bug fix

#28 [FEAT] Thymeleaf 관리자 페이지, 관련 코드 추가
  build.gradle
  src/main/java/com/rookies3/genaiquestionapp/admin/controller/AdminController.java
  src/main/java/com/rookies3/genaiquestionapp/auth/config/SecurityConfig.java
  src/main/java/com/rookies3/genaiquestionapp/config/AdminAccountInitializer.java
  src/main/resources/templates/admin/answer-records/list.html
  src/main/resources/templates/admin/answer-records/temp-log.txt
  src/main/resources/templates/admin/dashboard.html
  src/main/resources/templates/admin/layout.html
  src/main/resources/templates/admin/login.html
  src/main/resources/templates/admin/problems/list.html
  src/main/resources/templates/admin/users/edit.html
  src/main/resources/templates/admin/users/list.html
  src/main/resources/templates/admin/users/new.html
Labels: feature

#29 [FEAT] 사용자 맞춤 AI 챗봇 구현
  src/main/java/com/rookies3/genaiquestionapp/GenAiQuestionAppApplication.java
  src/main/java/com/rookies3/genaiquestionapp/ai/controller/AiController.java
  src/main/java/com/rookies3/genaiquestionapp/ai/controller/dto/AiDto.java
  src/main/java/com/rookies3/genaiquestionapp/ai/controller/dto/SubmitProblemDto.java
  src/main/java/com/rookies3/genaiquestionapp/ai/service/AiService.java
  src/main/java/com/rookies3/genaiquestionapp/auth/config/SecurityConfig.java
  src/main/java/com/rookies3/genaiquestionapp/exception/ErrorCode.java
  src/main/java/com/rookies3/genaiquestionapp/jwt/JwtAuthenticationFilter.java
Labels: feature

#31 [ETC] dockerignore 설정, Dockerfile 수정
  .dockerignore
  Dockerfile
Labels: etc

#33 [REFACTOR] rename userquestion, docker tag version up
  .github/workflows/main.yml
  src/main/java/com/rookies3/genaiquestionapp/admin/controller/AdminController.java
  src/main/java/com/rookies3/genaiquestionapp/userquestion/controller/UserQuestionController.java
  src/main/java/com/rookies3/genaiquestionapp/userquestion/controller/dto/UserQuestionChatDto.java
  src/main/java/com/rookies3/genaiquestionapp/userquestion/controller/dto/UserQuestionDto.java
  src/main/java/com/rookies3/genaiquestionapp/userquestion/entity/UserQuestion.java
  src/main/java/com/rookies3/genaiquestionapp/userquestion/entity/UserQuestionChat.java
  src/main/java/com/rookies3/genaiquestionapp/userquestion/repository/UserProblemChatRepository.java
  src/main/java/com/rookies3/genaiquestionapp/userquestion/repository/UserQuestionRepository.java
  src/main/java/com/rookies3/genaiquestionapp/userquestion/service/AIService.java
  src/main/java/com/rookies3/genaiquestionapp/userquestion/service/UserQuestionService.java
Labels: refactor

#38 [FIX] fix/37-edit-ddlauto-flyway
  .github/workflows/main.yml
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V1__initial_schema.sql
Labels: bug fix, refactor
